version: "3.9"

services:
  web:
    build: .
    container_name: poo_exam1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/web
    command: python manage.py runserver 0.0.0.0:8000